### ISSUE TITLE
Pagoda 2- rev B

### ISSUE THREAD

**Issue by Tomkanovik** [ep092/Pagoda-2-panel#1]
Hello can you make panelized gerber file of pagoda 2 rev B with 16 pagodas in one panel 10x10cm pcb, please? :)

**Comment by ep092** [comment]
Hello, do you search for https://github.com/ep092/Pagoda-2-panel/tree/master/panel_2b ?

**Comment by Tomkanovik** [comment]
I am sorry, i knew it, but it is mixed LHCP and RHCP and lot of people need only RHCP or LHCP. Please :)

**Comment by Tomkanovik** [comment]
And one more question you have drilled holes between the wheels to make the wheels slightly break? :)

**Comment by ep092** [comment]
the connections between the "wheels" are thin enough to cut with a diagonal plier. Drilled holes are not necessary.  I can upload a pagoda 2b panel with only LHCP and RHCP with the following silkscreen design https://github.com/ep092/Pagoda-2-panel/blob/master/pagoda-2_text_only/panel.png

Does that help?

**Comment by Tomkanovik** [comment]
With original printing design from marten would be better, but I'll be happy with this. I want the whole panel to be RHCP pagoda 2 rev B. :)

**Comment by Tomkanovik** [comment]
Please uoload it :) :) :)

**Comment by ep092** [comment]
i will upload it as soon as possible

**Comment by ep092** [comment]
https://github.com/ep092/Pagoda-2-panel/tree/master/panel_2b_RHCP
rev B RHCP only with my logo

**Comment by Tomkanovik** [comment]
Hello can you make panelized version of this maartens new antenna please? :)
http://www.maartenbaert.be/quadcopters/antennas/triple-feed-patch-antenna/

**Comment by ep092** [comment]
This would have been a new "issue".

I am planning to do a panel in the next view days. But there will be only parts for one antenna on a 10cmx10cm panel, because the bigger part of the antenna is about 6cmx6cm.

**Comment by Tomkanovik** [comment]
Small circle can be panelized :) I think 3x3 small wheels in one 10x10cm panel and big wheel will be separates.

**Comment by Tomkanovik** [comment]
For example I buy 10pcs (90pcs wheels) of panels of small wheels and 90pcs big wheels. Do you understand? :)
